config/routes.rb
Rpasswrd::Application.routes.draw do
  resources :codes
  resource :sessions
  resource :users

  match 'logout' => 'sessions#destroy'
  match 'login' => 'sessions#new'
  match 'signup' => 'users#new'
  match 'generate' => 'codes#generate'
  match 'api/getusers' => 'api#get_users'
  match 'api/getcodes' => 'api#get_codes'
  post 'api/addcode' => 'api#add_code'

  root :to => 'codes#index'

end

app/models/code.rb
class Code < ActiveRecord::Base
  attr_accessible :code, :is_deleted, :username, :password
  attr_encrypted :password, :key => 'zaqxswcdevfrbgtnhymjukilop1234567890'
  validates_presence_of(:code)
  validates_presence_of(:password)
  has_one(:user)
end

app/models/notifier.rb
class Notifier < ActionMailer::Base
  default :from => 'signup@tomwire.co.uk'

  # send a signup email to the user, pass in the user object that contains the user's email address
  def signup_email(user)
    @user = user
    @url  = 'https://secure.tomwire.co.uk/login'
    mail( :to => user.email,
    :subject => 'rpassword signup' )
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  has_secure_password
  validates_presence_of :password, :on => :create
  has_many(:codes)

  before_save do self.email.downcase! end

  def self.find_by_lower_email(email)
    User.find_by_email(email.downcase)
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  def get_users
    @users = User.all

    respond_to do |format|
      format.json { render json: @users }
    end
  end

  def add_code
    user = User.find_by_email(params[:email])

    code = Code.find_by_code(params[:code])

    if !code then
      code = Code.new
      code.user_id = user.id
      code.password = params[:password]
      code.username = params[:username]
      code.code = params[:code]
      code.is_deleted = false
      code.save
    end


    respond_to do |format|
      format.json { render json: user }
    end
  end
  
  def get_codes
    if params[:key] == 'iorqo893fnkwk' then
      @codes = Code.where('is_deleted = ?', false)

      respond_to do |format|
        format.json { render :partial => 'api/get_codes.json.erb' } #, @codes.to_json(:only => [:id, :code, :password, :username, :user_id]) }
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :require_login #, :except => [:get_users, :add_code]

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_login
    unless current_user
      redirect_to new_sessions_path
    end
  end

  helper_method :current_user
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
  skip_before_filter :require_login, :only => :generate

  # GET /codes
  # GET /codes.json
  def index
    @user_id = session[:user_id]
    @codes = Code.where('user_id = ? and is_deleted = ?', @user_id, false).order('LOWER(code)') #.find_by_user_id(@user_id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @codes }
    end
  end

  # GET /codes/1
  # GET /codes/1.json
  def show
    @code = Code.find_by_id_and_user_id(params[:id], session[:user_id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @code }
    end
  end

  # GET /codes/new
  # GET /codes/new.json
  def new
    @code = Code.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @code }
    end
  end

  # GET /codes/1/edit
  def edit
    @code = Code.find_by_id_and_user_id(params[:id], session[:user_id])
  end

  # POST /codes
  # POST /codes.json
  def create
    @code = Code.new(params[:code])
    @code.user_id = session[:user_id]

    respond_to do |format|
      if @code.save
        format.html { redirect_to codes_path, notice: 'Code was successfully created.' }
        format.json { render json: @code, status: :created, location: @code }
      else
        format.html { render action: "new" }
        format.json { render json: @code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /codes/1
  # PUT /codes/1.json
  def update
    @code = Code.find_by_id_and_user_id(params[:id], session[:user_id])

    respond_to do |format|
      if @code.update_attributes(params[:code])
        format.html { redirect_to codes_url, notice: 'Code was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /codes/1
  # DELETE /codes/1.json
  def destroy
    @code = Code.find_by_id_and_user_id(params[:id], session[:user_id])
    @code.destroy

    respond_to do |format|
      format.html { redirect_to codes_url, notice: 'Code deleted' }
      format.json { head :no_content }
    end
  end


  def generate
    random = [*('a'..'z'),*('0'..'9')].shuffle[0,12].join

    @code = '{ "randomCode" : "' + random + '" }'

    respond_to do |format|
      format.json { render json: @code }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_filter :require_login
  def new
  end

  def create
    user = User.find_by_lower_email(params[:email].downcase)
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_filter :require_login
  def new
    @user = User.new
  end

  skip_before_filter :require_login
  def create
    @user = User.new(params[:user])
    if @user.save
      Notifier.signup_email(@user).deliver
      redirect_to root_url, :notice => 'Signed up!'
    else
      render 'new'
    end
  end

end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/codes/_form.html.erb
<%= form_for @code, html: {class: "form-horizontal"} do |f| %>
  <% if @code.errors.any? %>
      <div class="alert alert-warning alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong>Warning! <%= pluralize(@code.errors.count, "error") %> prohibited this from being saved:</strong>
        <ul>
            <% @code.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
         <% end %>
      </ul>
    </div>
  <% end %>

      <div class="form-group">
        <label class='col-lg-2 control-label'>Code</label>
        <div class="col-lg-4">
          <%= f.text_field :code, :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <label class='col-lg-2 control-label'>Password</label>
        <div class="col-lg-4">
          <%= f.text_field :password, :class => 'form-control' %>
        </div>
        <div class='col-lg-2'>
          <button type='button' id='generate' class="btn">Generate</button>
        </div>
      </div>

      <div class="form-group">
        <label class='col-lg-2 control-label'>Username</label>
        <div class="col-lg-4">
          <%= f.text_field :username, :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group deleted">
        <label class='col-lg-2 control-label'>Deleted</label>
        <div class="col-lg-4">
          <%= f.check_box :is_deleted, :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <div class='col-lg-2'></div>
        <div class="col-lg-4">
          <%= f.submit 'Save', :class => 'btn btn-primary' %>
          <%= link_to 'Back', codes_path, :class => 'btn btn-default' %>
        </div>
      </div>
<% end %>

app/views/codes/edit.html.erb
<fieldset>
  <legend>Edit</legend>
  <%= render 'form' %>
</fieldset>

<script>
    $(function () {
        $('#generate').hide();
    });
</script>

app/views/codes/index.html.erb
<fieldset>
  <legend>Listing codes</legend>

<table class='table table-striped table-bordered'>
  <thead>
  <tr>
    <th>Code</th>
    <th></th>
  </tr>
  </thead>
    <tbody>
        <% @codes.each do |code| %>
            <tr>
                <td><%= code.code %></td>
                <td>
                  <div class="visible-xs">
                    <div class="btn-group">
                      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                        Action <span class="caret"></span>
                      </button>
                      <ul class="dropdown-menu" role="menu">
                        <li><%= link_to 'Show', code %></li>
                        <li><%= link_to 'Edit', edit_code_path(code) %></li>
                        <li class="divider"></li>
                        <li><%= link_to 'Destroy', code, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                      </ul>
                    </div>
                  </div>
                  <div class="hidden-xs">
                    <%= link_to 'Show', code, :class => 'btn btn-default' %>
                    <%= link_to 'Edit', edit_code_path(code), :class=>'btn btn-default' %>
                    <%= link_to 'Destroy', code, method: :delete, data: { confirm: 'Are you sure?' }, :class=>'btn btn-danger' %>
                  </div>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

<br />
</fieldset>

app/views/codes/new.html.erb
<fieldset>
  <legend>New</legend>
  <%= render 'form' %>
</fieldset>

<script>
    $(function () {
        var options = new Object();
        var g = new generator(options);

        $('.deleted').hide();

  });
</script>

app/views/codes/show.html.erb
<form class='form-horizontal'>

<div class="form-group">
  <label class='col-lg-2 control-label'>Code</label>
  <div class="col-lg-4">
    <pre><%= @code.code %></pre>
  </div>
</div>

<div class="form-group">
  <label class='col-lg-2 control-label'>Password</label>
  <div class="col-lg-4">
    <pre><%= @code.password %></pre>
  </div>
</div>


  <%if !@code.username.blank? %>
      <div class="form-group">
        <label class='col-lg-2 control-label'>Username</label>
        <div class="col-lg-4">
          <pre><%= @code.username %></pre>
        </div>
      </div>
  <%end%>


  <div class="form-group">
    <div class='col-lg-2'></div>
    <div class="col-lg-4">
    <%= link_to 'Edit', edit_code_path(@code), :class => 'btn btn-default' %>
    <%= link_to 'Back', codes_path, :class => 'btn btn-default' %>
    </div>
  </div>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="utf-8">

    <title>Rpasswrd</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', :media => 'all' %>
  <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
    <script src='//code.jquery.com/jquery-1.10.1.min.js'></script>
  <%= csrf_meta_tags %>


    <script src='//cdnjs.cloudflare.com/ajax/libs/toastr.js/1.3.1/js/toastr.min.js'></script>
    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/1.3.1/css/toastr.min.css" rel='stylesheet' />
</head>
<body>


<!-- Static navbar -->
<div class="navbar navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">rpassword</a>
  </div>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
      <%if @current_user%>
          <li>
            <a href='/logout'>Log Out</a>
          </li>
          <li>
            <%= link_to 'New Code', new_code_path %>
          </li>
      <%else%>
          <li>
            <a href='/signup'>Sign Up</a>
          </li>
          <li>
            <a href='/login'>Log In</a>
          </li>
      <%end%>
    </ul>
  </div><!--/.nav-collapse -->
</div>


    <div class='container'>
    <%if flash[:alert] %>
      <script>
          toastr.error('<%= flash[:alert] %>');
      </script>
    <%end%>

    <%if flash[:notice] %>
      <script>
          toastr.success('<%= flash[:notice] %>');
      </script>
    <%end%>

    <%= yield %>
    </div>

    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
</body>
</html>

app/views/notifier/signup_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Welcome to rpasswrd!</h1>
    <p>
      You have successfully signed up to rpasswrd,
      your username is: <%= @user.email %>.<br/>
    </p>
    <p>
      Please validate your account by following <a href='<%= @url %>'>this link</a>.
    </p>
    <p>Thanks for joining and have a great day!</p>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for @user, html: {class: "form-horizontal"} do |f| %>
    <% if @user.errors.any? %>
        <div class="alert alert-warning alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <fieldset>
      <legend>Sign Up</legend>

      <div class="form-group">
        <label class='col-lg-2 control-label'>Email</label>
        <div class="col-lg-4">
          <%= f.email_field :email, :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <label class='col-lg-2 control-label'>Password</label>
        <div class="col-lg-4">
          <%= f.password_field :password, :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <label class='col-lg-2 control-label'>Confirm Password</label>
        <div class="col-lg-4">
          <%= f.password_field :password_confirmation, :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <div class='col-lg-2'></div>
        <div class="col-lg-4">
          <%= f.submit 'Sign Up', :class => 'btn btn-primary' %>
        </div>
      </div>

      </fieldset>
<% end %>